Manual Upload - Error pushing in Bash
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/ltkdobbs/election_analysis.git'

hint: Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes (e.g., 'git pull ...') before pushing again.

See the 'Note about fast-forwards' in 'git push --help' for details.